exp_name: "numint" # Experiment name 
seed: 42 # Random seed to use for experiments
ignore_cache: true # If true, expert preprocessing is recomputed, even when it was already done and stored
run_and_evaluate: true # If true, the experiment is run and evaluated, otherwise only the runs are executed without evaluation

benchmark:
    name: "TabArena" # One of: [TabZilla, TabArena, Grinsztajn]
    subset: ["Food_Delivery_Time"]
    # subset: ['coil2000_insurance_policies', 'Diabetes130US', 'Food_Delivery_Time', 'HR_Analytics_Job_Change_of_Data_Scientists', 'kddcup09_appetency', 'Marketing_Campaign', 'qsar-biodeg', 'students_dropout_and_academic_success', 'MIC'] #["concrete_compressive_strength", "Food_Delivery_Time"] # If subset is not None, only these datasets are used, otherwise all datasets in the benchmark are used
    # subset: ["Bank_Customer_Churn", "concrete_compressive_strength", "credit_card_clients_default", "customer_satisfaction_in_airline","Food_Delivery_Time", "houses", "HR_Analytics_Job_Change_of_Data_Scientists", "students_dropout_and_academic_success", "MIC", "qsar-biodeg", "APSFailure", "Bioresponse"]
    # subset: ["Bank_Customer_Churn", "concrete_compressive_strength", "credit_card_clients_default", "customer_satisfaction_in_airline","Food_Delivery_Time", "houses", "HR_Analytics_Job_Change_of_Data_Scientists", "students_dropout_and_academic_success", "MIC", "qsar-biodeg"]
    # subset: ["electricity", "nomao", "artificial-characters", "SpeedDating", "airlines", "elevators"]
    # subset: ["Bike_Sharing_Demand", "nyc-taxi-green-dec-2016", "particulate-matter-ukair-2017", "seattlecrime6", "Allstate_Claims_Severity", "Airlines_DepDelay_1M", "elevators", "Ailerons", "electricity", "eye_movements", "default-of-credit-card-clients", "road-safety", "california", "heloc"]
    # subset: ['anneal', 'APSFailure', 'Bioresponse', 'blood-transfusion-service-center', 'churn', 'coil2000_insurance_policies', 'Diabetes130US', 'heloc', 'hiva_agnostic', 'HR_Analytics_Job_Change_of_Data_Scientists', 'in_vehicle_coupon_recommendation', 'kddcup09_appetency', 'Marketing_Campaign', 'NATICUSdroid', 'polish_companies_bankruptcy', 'qsar-biodeg', 'QSAR-TID-11', 'seismic-bumps', 'splice', 'students_dropout_and_academic_success', 'superconductivity', 'taiwanese_bankruptcy_prediction', 'MIC']
    # CATENGINEER:
    # subset: ['kddcup09_appetency', 'Amazon_employee_access', 'in_vehicle_coupon_recommendation','SDSS17']
    # GROUPBY
    # subset: ['students_dropout_and_academic_success', 'Diabetes130US', 'qsar-biodeg', 'credit-g', 'churn', 'bank-marketing', 'HR_Analytics_Job_Change_of_Data_Scientists', 'diamonds', 'SDSS17', 'Food_Delivery_Time', 'wine_quality', 'healthcare_insurance_expenses','Fitness_Club', 'Another-Dataset-on-used-Fiat-500']
    # subset: ['MIC', 'kddcup09_appetency', 'Diabetes130US', 'Amazon_employee_access', 'students_dropout_and_academic_success', 'HR_Analytics_Job_Change_of_Data_Scientists', 'online_shoppers_intention', 'in_vehicle_coupon_recommendation', 'coil2000_insurance_policies', 'Marketing_Campaign', 'SDSS17']
    # CATDROP:
    # subset: ['MIC', 'Diabetes130US'] #, 'Food_Delivery_Time', 'splice', 'seismic-bumps', 'churn', 'kddcup09_appetency'] 
    # DROP
    # subset: ['hiva_agnostic', 'Bioresponse', 'kddcup09_appetency', 'MIC','Diabetes130US', 'anneal', 'qsar-biodeg']
    # CATFREQ
    # subset: ['kddcup09_appetency', 'Diabetes130US', 'Amazon_employee_access',
    #    'students_dropout_and_academic_success', 'Marketing_Campaign',
    #    'HR_Analytics_Job_Change_of_Data_Scientists', 'Is-this-a-good-customer',
    #    'healthcare_insurance_expenses', 'churn',
    #    'in_vehicle_coupon_recommendation']
    # CAT Int
    # subset: ['Amazon_employee_access']
    # CAT groupby
    # subset: ['kddcup09_appetency', 'MIC', 'Diabetes130US',
    #    'customer_satisfaction_in_airline', 'Amazon_employee_access',
    #    'online_shoppers_intention', 'coil2000_insurance_policies']
    # NUMINT
    subset: ['jm1', 'students_dropout_and_academic_success', 'APSFailure',
       'polish_companies_bankruptcy', 'hazelnut-spread-contaminant-detection',
       'credit_card_clients_default', 'churn', 'wine_quality',
       'physiochemical_protein', 'houses', 'Diabetes130US', 'SDSS17',
       'maternal_health_risk', 'Food_Delivery_Time', 'Is-this-a-good-customer',
       'Another-Dataset-on-used-Fiat-500', 'blood-transfusion-service-center',
       'E-CommereShippingData']
    outer_folds: "full" # "full" for whole benchmark, or int for user-specified number of outer folds to use in cross-validation
    repeats: "full" # Number of repeats for outer folds, if outer_folds is not "full"
    inner_folds: 8 # Number of inner folds for bagging
    time_limit: 3600 # Time limit for each model in seconds. time_limit=3600 was used in the TabArena 2025 paper
    # fold_fitting_strategy: "sequential_local"

model:
    name: "GBM" # 
    hyperparameters: null  # Model hyperparameters to override the default configurations
      # n_estimators: 4000
      # patience: 200

preprocessing:
    use_ftd: false
    input_format: "openml" # One of [openml, csv]
    
    
hpo: 
    n_trials: 0 # How many random search trials to run in addition to the default config
    # ensemble_trials: false # If true, the predictions of all trials are ensembled

hardware:
    # device: "cuda" # Device to use, currently only "cuda" tested
    # gpus: "0" # Which GPU nodes in cluster to use
    # folds_parallel: 1 # How many CV folds to train in parallel on one node


